import type {
  CanteenOrder,
  ChatMessage,
  Conversation,
  Employee,
  ScheduleRequest,
  Task,
} from "@/lib/types";

export const employees: Employee[] = [
  {
    id: "NV-001",
    name: "Nguyễn Minh Anh",
    email: "minhanh@hdg.vn",
    phone: "090 123 4567",
    role: "Quản trị viên",
    department: "Ban điều hành",
    status: "active",
    joinedAt: "12/03/2022",
    shift: "Hành chính",
    initial: "MA",
    tone: "red",
  },
  {
    id: "NV-014",
    name: "Trần Hoàng Nam",
    email: "hoangnam@hdg.vn",
    phone: "091 224 8821",
    role: "Quản lý",
    department: "Vận hành",
    status: "active",
    joinedAt: "04/08/2023",
    shift: "Ca sáng",
    initial: "HN",
    tone: "violet",
  },
  {
    id: "NV-022",
    name: "Lê Thu Hương",
    email: "thuhuong@hdg.vn",
    phone: "093 526 1174",
    role: "Nhân viên",
    department: "Nhân sự",
    status: "active",
    joinedAt: "18/01/2024",
    shift: "Hành chính",
    initial: "TH",
    tone: "blue",
  },
  {
    id: "NV-027",
    name: "Phạm Quốc Bảo",
    email: "quocbao@hdg.vn",
    phone: "098 640 0217",
    role: "Bếp trưởng",
    department: "Căn tin",
    status: "active",
    joinedAt: "09/11/2023",
    shift: "Ca sáng",
    initial: "QB",
    tone: "amber",
  },
  {
    id: "NV-031",
    name: "Đỗ Ngọc Linh",
    email: "ngoclinh@hdg.vn",
    phone: "097 110 5286",
    role: "Thu ngân",
    department: "Căn tin",
    status: "offline",
    joinedAt: "21/02/2024",
    shift: "Ca chiều",
    initial: "NL",
    tone: "emerald",
  },
  {
    id: "NV-035",
    name: "Vũ Gia Huy",
    email: "giahuy@hdg.vn",
    phone: "096 482 1910",
    role: "Nhân viên",
    department: "Kỹ thuật",
    status: "leave",
    joinedAt: "16/05/2024",
    shift: "Hành chính",
    initial: "GH",
    tone: "cyan",
  },
  {
    id: "NV-042",
    name: "Bùi Khánh Vy",
    email: "khanhvy@hdg.vn",
    phone: "090 836 6420",
    role: "Phục vụ",
    department: "Căn tin",
    status: "active",
    joinedAt: "07/10/2024",
    shift: "Ca sáng",
    initial: "KV",
    tone: "cyan",
  },
  {
    id: "NV-048",
    name: "Hoàng Đức Long",
    email: "duclong@hdg.vn",
    phone: "092 518 7634",
    role: "Nhân viên",
    department: "Kinh doanh",
    status: "offline",
    joinedAt: "14/01/2025",
    shift: "Hành chính",
    initial: "ĐL",
    tone: "slate",
  },
];

export const tasks: Task[] = [
  {
    id: "CV-1082",
    title: "Hoàn thiện báo cáo vận hành tháng 8",
    description: "Tổng hợp số liệu của các bộ phận và gửi Ban điều hành.",
    assignee: "Trần Hoàng Nam",
    assigneeInitial: "HN",
    department: "Vận hành",
    due: "28/08/2026 · 17:30",
    status: "in_progress",
    priority: "high",
    progress: 68,
  },
  {
    id: "CV-1081",
    title: "Cập nhật hồ sơ nhân sự quý III",
    description: "Rà soát thông tin liên hệ và hợp đồng còn thiếu.",
    assignee: "Lê Thu Hương",
    assigneeInitial: "TH",
    department: "Nhân sự",
    due: "30/08/2026 · 16:00",
    status: "review",
    priority: "medium",
    progress: 90,
  },
  {
    id: "CV-1078",
    title: "Kiểm kê nguyên liệu cuối tuần",
    description: "Đối chiếu tồn kho thực tế với số liệu trên hệ thống.",
    assignee: "Phạm Quốc Bảo",
    assigneeInitial: "QB",
    department: "Căn tin",
    due: "29/08/2026 · 20:00",
    status: "todo",
    priority: "high",
    progress: 10,
  },
  {
    id: "CV-1075",
    title: "Bảo trì máy chấm công tầng 2",
    description: "Kiểm tra kết nối và cập nhật firmware thiết bị.",
    assignee: "Vũ Gia Huy",
    assigneeInitial: "GH",
    department: "Kỹ thuật",
    due: "01/09/2026 · 10:00",
    status: "todo",
    priority: "low",
    progress: 0,
  },
  {
    id: "CV-1072",
    title: "Thiết lập thực đơn tuần mới",
    description: "Cân đối món ăn, giá và lượng nguyên liệu dự kiến.",
    assignee: "Phạm Quốc Bảo",
    assigneeInitial: "QB",
    department: "Căn tin",
    due: "27/08/2026 · 14:00",
    status: "done",
    priority: "medium",
    progress: 100,
  },
];

export const scheduleRequests: ScheduleRequest[] = [
  {
    id: "YC-241",
    employee: "Lê Thu Hương",
    initial: "TH",
    department: "Nhân sự",
    kind: "Đăng ký lịch tuần",
    schedule: "31/08 – 06/09 · Hành chính",
    submittedAt: "12 phút trước",
    status: "pending",
  },
  {
    id: "YC-240",
    employee: "Bùi Khánh Vy",
    initial: "KV",
    department: "Căn tin",
    kind: "Đổi ca làm",
    schedule: "29/08 · Sáng → Chiều",
    submittedAt: "35 phút trước",
    status: "pending",
  },
  {
    id: "YC-239",
    employee: "Hoàng Đức Long",
    initial: "ĐL",
    department: "Kinh doanh",
    kind: "Làm việc từ xa",
    schedule: "01/09 · Cả ngày",
    submittedAt: "1 giờ trước",
    status: "pending",
  },
  {
    id: "YC-238",
    employee: "Đỗ Ngọc Linh",
    initial: "NL",
    department: "Căn tin",
    kind: "Xin đi muộn",
    schedule: "28/08 · 30 phút",
    submittedAt: "Hôm qua",
    status: "approved",
  },
];

export const canteenOrders: CanteenOrder[] = [
  {
    id: "order-1",
    code: "HDG-0828",
    table: "Bàn 08",
    customer: "Nguyễn Văn Hòa",
    items: ["Cơm gà xối mỡ × 1", "Canh rong biển × 1"],
    total: 72000,
    createdAt: "11:42",
    status: "new",
    payment: "paid",
  },
  {
    id: "order-2",
    code: "HDG-0827",
    table: "Mang đi",
    customer: "Trần Mỹ Duyên",
    items: ["Bún bò Huế × 2", "Trà tắc × 2"],
    total: 118000,
    createdAt: "11:38",
    status: "confirmed",
    payment: "paid",
  },
  {
    id: "order-3",
    code: "HDG-0826",
    table: "Bàn 03",
    customer: "Phòng Kỹ thuật",
    items: ["Cơm sườn nướng × 3", "Nước suối × 3"],
    total: 189000,
    createdAt: "11:34",
    status: "cooking",
    payment: "unpaid",
  },
  {
    id: "order-4",
    code: "HDG-0825",
    table: "Bàn 11",
    customer: "Lê Thanh Tùng",
    items: ["Mì xào bò × 1", "Cà phê sữa × 1"],
    total: 79000,
    createdAt: "11:29",
    status: "ready",
    payment: "paid",
  },
  {
    id: "order-5",
    code: "HDG-0824",
    table: "Bàn 05",
    customer: "Vũ Ngọc Mai",
    items: ["Cơm cá kho × 1"],
    total: 55000,
    createdAt: "11:20",
    status: "completed",
    payment: "paid",
  },
];

export const conversations: Conversation[] = [
  {
    id: "hoang-nam",
    name: "Trần Hoàng Nam",
    role: "Quản lý vận hành",
    initial: "HN",
    online: true,
    lastMessage: "Em đã cập nhật báo cáo rồi ạ.",
    time: "11:28",
    unread: 2,
  },
  {
    id: "thu-huong",
    name: "Lê Thu Hương",
    role: "Chuyên viên nhân sự",
    initial: "TH",
    online: true,
    lastMessage: "Lịch phỏng vấn đã được xác nhận.",
    time: "10:46",
    unread: 0,
  },
  {
    id: "quoc-bao",
    name: "Phạm Quốc Bảo",
    role: "Bếp trưởng",
    initial: "QB",
    online: false,
    lastMessage: "Kho còn thiếu 2 mặt hàng.",
    time: "09:15",
    unread: 0,
  },
  {
    id: "ngoc-linh",
    name: "Đỗ Ngọc Linh",
    role: "Thu ngân",
    initial: "NL",
    online: false,
    lastMessage: "Dạ em đã nhận được thông tin.",
    time: "Hôm qua",
    unread: 0,
  },
];

export const initialMessages: Record<string, ChatMessage[]> = {
  "hoang-nam": [
    {
      id: "m1",
      sender: "member",
      content: "Chào anh, em gửi nhanh tình hình vận hành sáng nay nhé.",
      time: "10:52",
    },
    {
      id: "m2",
      sender: "admin",
      content: "Ừ, em cập nhật giúp anh số nhân sự check-in và các việc còn vướng.",
      time: "10:54",
    },
    {
      id: "m3",
      sender: "member",
      content: "Hiện có 126 người đã check-in, 7 trường hợp chưa ghi nhận. Ba yêu cầu lịch vẫn đang chờ duyệt.",
      time: "11:02",
    },
    {
      id: "m4",
      sender: "admin",
      content: "Tốt. Em ưu tiên xử lý ba yêu cầu đó trước 14:00 và ghi chú lại giúp anh.",
      time: "11:06",
    },
    {
      id: "m5",
      sender: "member",
      content: "Em đã cập nhật báo cáo rồi ạ.",
      time: "11:28",
    },
  ],
  "thu-huong": [
    {
      id: "h1",
      sender: "member",
      content: "Em đã hoàn tất danh sách ứng viên vòng hai.",
      time: "10:31",
    },
    {
      id: "h2",
      sender: "admin",
      content: "Cảm ơn Hương. Nhớ gửi lịch cho các trưởng bộ phận nhé.",
      time: "10:34",
    },
    {
      id: "h3",
      sender: "member",
      content: "Lịch phỏng vấn đã được xác nhận.",
      time: "10:46",
    },
  ],
  "quoc-bao": [
    {
      id: "b1",
      sender: "member",
      content: "Kho còn thiếu 2 mặt hàng: dầu ăn và sữa tươi.",
      time: "09:15",
    },
  ],
  "ngoc-linh": [
    {
      id: "l1",
      sender: "admin",
      content: "Linh kiểm tra giúp anh đối soát ca chiều nhé.",
      time: "Hôm qua · 16:40",
    },
    {
      id: "l2",
      sender: "member",
      content: "Dạ em đã nhận được thông tin.",
      time: "Hôm qua · 16:42",
    },
  ],
};

export const weeklyAttendance = [82, 88, 85, 93, 91, 48, 32];
export const revenueSeries = [12, 18, 15, 24, 22, 31, 28, 36, 33, 42, 39, 48];
